apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: artemis
  labels:
    app.kubernetes.io/name: artemis
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: artemis
  labels:
    app.kubernetes.io/name: artemis
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: artemis
  labels:
    app.kubernetes.io/name: artemis
    app.kubernetes.io/component: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 2Gi
