apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bentopdf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.example.net/infrastructure/nl/production.git
    targetRevision: main
    path: k8s/argocd-apps/bentopdf
  destination:
    server: https://kubernetes.default.svc
    namespace: bentopdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
